name: pdflatex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-bibtex-extra texlive-fonts-recommended texlive-latex-extra

      - name: Compile LaTeX document (pdflatex)
        run: |
          pdflatex CambridgeUS-c.tex  
          bibtex CambridgeUS-c-blx      
          pdflatex CambridgeUS-c.tex  
          pdflatex CambridgeUS-c.tex  

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-pdf
          path: main.pdf  
